# Site settings
title: Elena Sofia Ruzzetti
email: elena.sofia.ruzzetti@uniroma2.it
description: Academic webpage of Elena Sofia Ruzzetti
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Elena Sofia Ruzzetti<br/>
  Pd.D. Student in Data Science<br/>
  Human Centric ART Lab, University of Rome Tor Vergata

location: >
  University of Rome Tor Vergata<br/>
  Department of Management Engineering<br/>
  <a href="https://humancentricart.github.io/">Human Centric ART Lab</a>

contact: >
  <a href="mailto:elena.sofia.ruzzetti@uniroma2.it" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact me via email</a> <br/>
  <a href="https://github.com/elenasofia98"><i class="fa fa-github fa-1x"></i> Some Projects on GitHub</a> <br/>
  <a href="https://www.linkedin.com/in/elena-sofia-ruzzetti/"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16"><path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z"></path></svg> Get in touch on LinkedIn </a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  #- name: talks
  #- name: research
  #- name: software
  #- name: team
  #- name: teaching
  #- name: blogs

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Ruzzetti
  first_name: [Elena Sofia]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
