# Site settings
title: Elena Sofia Ruzzetti
email: elena.sofia.ruzzetti@uniroma2.it
description: Academic webpage of Elena Sofia Ruzzetti
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Elena Sofia Ruzzetti<br/>
  Pd.D. Student in Data Science<br/>
  University of Rome Tor Vergata

location: >
  University of Rome Tor Vergata<br/>
  Department of Management Engineering<br/>
  <a href="https://humancentricart.github.io/">Human Centric ART Lab</a>

contact: >
  <a href="mailto:elena.sofia.ruzzetti@uniroma2.it" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact me via email</a> <br/>
  <a href="https://github.com/elenasofia98"><i class="fa fa-github fa-1x"></i> Some Projects on GitHub</a>
  <a href="https://www.linkedin.com/in/elena-sofia-ruzzetti/"> <i class="bi bi-linkedin"></i> Get in touch on LinkedIn</a>

# Pages shown in navbar
nav_pages:
  #- name: about
  - name: publications
  #- name: talks
  #- name: research
  #- name: software
  #- name: team
  #- name: teaching
  #- name: blogs

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Ruzzetti
  first_name: [Elena Sofia]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
